### ISSUE TITLE
Console won't launch on game start, dependent mod won't work

### ISSUE THREAD

**Issue by duetschlandftw** [Norbyte/bg3se#1]
No console opens when I launch BG3 (Steam, latest patch and hotfix), and in the main menu I get an alert saying the SE can't update, accompanied by "HTTP error 403". I extracted the files from the latest release (post-hotfix 15) to BaldursGate3/bin. My other mod works, but the mod dependent on the SE doesn't (mods are managed by vortex and the modsettings.lsx seems to match what the creator specified), which leads me to think this an issue with bg3se specifically.

**Comment by Norbyte** [comment]
Hi,

Did you download the latest launcher version? https://github.com/Norbyte/bg3se/releases

If so, can you check if you extracted the two .json files as well, not just DWrite.dll?

I'll check if I can see in the logs which URLs caused a 403 hit on the update server.

**Comment by duetschlandftw** [comment]
I did, the one from 7 days ago. To be 100% sure, I just downloaded from your link and extracted again (replacing the 3 files), still no console.

Looking in /bin, I see the 2 .json files (ScriptExtenderSettings and ScriptExtenderUpdaterConfig), as well as DWrite.dll

**Comment by Norbyte** [comment]
Can you check if launching the game directly via bg3.exe or bg3_dx11.exe works? (As opposed to launching via Steam)
If so, I have a fix in progress that should solve the issue.

**Comment by duetschlandftw** [comment]
That completely fixed it! I launched from BG3.exe first (I assume Vulkan?), and the console appeared at startup. The dependent mod also worked. After that I launched from the launcher with DX11, and again console and working mod. I also restarted and launched straight from steam/the launcher, and this time the console appeared and the mod worked. I'll go ahead and close the issue; if you want any sort of platform or version info please reach out.

**Comment by tnsolley** [comment]
Just encountered this error message, I've had no issues with SE or BG3 (modded) before now. Only thing that I can think of as having changed would be the commit from yesterday?

I'm launching the game from Vortex, the error message
"Script Extender Updater Error
Script Extender update failed.
Unable to download manifest: HTTP error 403."
Appears as soon as the "launch" button (upper left corner) is clicked. I haven't gone past the title screen yet, since I'm afraid to brick my save file (doing an Honor Mode run). Should I expect this to be a temporary issue?
