### ISSUE TITLE
Game stuck at 100% loading

### ISSUE THREAD

**Issue by jsheydman** [Norbyte/bg3se#112]
After installing the updates for hotfix 9 and SE i'm having this issue on the debugger

I don't have any idea about what is this but i would be thankful if anybody could help :D

![image](https://github.com/Norbyte/bg3se/assets/145373994/9978f50a-dd4e-4f97-a1f9-988dab740e24)

**Comment by knorke3** [comment]
I suspect that it's already too late for help here but i've run into this myself multiple times by now while playing modded on linux. Every time it's happened, i had a misconfigured %localappdata%/Larian Studios/Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx due to me messing with it by hand. If anyone else runs into this and finds this via google, i'd strongly recommend checking that file for mismatched tags, typos in any fields, and mods that are either missing or shouldn't be there.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
