### ISSUE TITLE
Could not make Mods work with Script Extender in Bg3 Mod manager.

### ISSUE THREAD

**Issue by dakingp1n** [Norbyte/bg3se#124]
I have a problem where the 5eSpells would not work because it "Requires Script Extender V5 or higher", even though I already downloaded the latest one from the tools tab in bg3mm. 
![image_2023-11-01_012654777](https://github.com/Norbyte/bg3se/assets/149528148/61323a8e-c157-4676-aad7-33d34106b43f)

Whenever I go in-game, I would find this message.
![image](https://github.com/Norbyte/bg3se/assets/149528148/8a4aface-2c0e-4712-94bf-d6397d0ff567)
Even though I have checked whether or not I have the latest version available. 

I also installed the script extender manually several times, including the one where you add a json file named "ScriptExtenderSettings" into the bin folder.

Its been several hours and I could not get this to work for the life of me. 

If anyone has any suggestions they are greatly appreciated. 

UPDATE: I have done further experimentation since I'm a noob at this and found out that its not just 5eSpells but every other mod which requires Script Extender.
![image](https://github.com/Norbyte/bg3se/assets/149528148/d3a8b969-06cc-4fca-abd9-d56d40868664)
![image](https://github.com/Norbyte/bg3se/assets/149528148/a65793d6-879f-457e-b842-e8c98da9950b)

**UPDATE2: I am a super dumdum and I needed to update my game.**

**Comment by quillbee69** [comment]
I'm having a similar problem, extracting the script works fine in the mod manager but on the mod that requires it it says: [MISSING] Requires Script Extender v1 or Higher
It's like it can't find what version the script is or something

**Comment by dakingp1n** [comment]
I'm not sure if the mod can't find the script or the VERSION the script is, because I have tried to use older 5eSpells mods which require different versions of the script extender namely, "v1" or "v4". It still doesn't work in the end, the same Script Extender Updater Error keeps popping up.

**Comment by uFWraith** [comment]
I had this same thing but after I launched the game and then quit out, the Mod Manager was no longer displaying that error. I am guessing that the script extender requires the game to be launched once after installing to properly report the version or something.

**Comment by Akotowicz** [comment]
I have the same problem that the Mofd manager doesn't see the Script extender. I did exactly what you said to launch the game after installing the script extender, i got the same pop up "script extender update failed" and after loading the game i quit i . Opended

**Comment by BelegCufea** [comment]
I don't know what BG3MM is checking when determining BGSE version, but it seems that now it really checks if it is installed in `%AppData%/Local/BG3ScriptExtender` (Win 10)/ `%LocalAppData%/BG3ScriptExtender` (Win 11).

The Updater (the `DWrite.dll` file you downloaded form [here](https://github.com/Norbyte/bg3se/releases)) will install/update Script Extender into that folder every time you RUN the game. So you need to run the game at least once after isntalling BGSE.

If you have problem with updating BGSE (known issue), You can use offline version of BGSE available on [https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip](https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip). Unpack both files into `bin` folder.
This version has two problems:
- You will need to download and copy the files manualy when new version of Script Extender is available. It will not check for new version. All versions of Script extender are listed in https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json file. Newest is the latest.
- BG3MM will still shows the error

You can also try to unzip and copy files of v7 of BGSE (latest as of writing this post) from [mediafire](https://www.mediafire.com/file/bfkllmqbwu0gieb/BG3ScriptExtender.zip/file) into above mentioned folder (%AppData%...). It is a copy of current version of BGSE on my computer.
You will not get the BG3MM error but you will stil get the BGSE update error when running the game.

**Comment by Akotowicz** [comment]
Omgg it works, Thank you so much❤️

**Comment by Zapzinsz** [comment]
What do I do if it's not installed in %AppData%/Local/ ?

**Comment by sclient** [comment]
> I don't know what BG3MM is checking when determining BGSE version, but it seems that now it really checks if it is installed in `%AppData%/Local/BG3ScriptExtender` (Win 10)/ `%LocalAppData%/BG3ScriptExtender` (Win 11).

OK, it seems like my issue is still being on HF6. Not ready to update yet, but everything was working fine before, and I changed nothing, and now all of a sudden, the MM just cant detect the SE. Tried everything in your post, even the manual install and nothing. Perhaps you have access to the 9/4 version of the manual installer?

**Comment by SheeraDarkphoenix** [comment]
It's not working with Vortex Mod Manager either. Crashes my game right at the Character Creation. So I am just waiting patiently for the new updater to be released so I can go back to playing my game.

**Comment by BurhanDanger** [comment]
@BelegCufea 

> I don't know what BG3MM is checking when determining BGSE version
	
From what I gathered it checks the version numbers from the "BG3ScriptExtender.dll" files in "%AppData%\Local\BG3ScriptExtender\BG3ScriptExtender\*\*"

> * BG3MM will still shows the error

Following are some things that I did to sidestep these errors and show correct version in BG3MM using the offline/standalone version of BGSE.

1. Download latest version of BG3SE from (https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip) since I have latest game version too. 
In case someone has older game version, they can get older supported BG3SE from (https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json). (Download the "URL" link, open the .package file in 7zip for eg)

2. Extract both files from ManualInstall.zip to "Baldur's Gate 3\bin" folder. (Also if console is needed then you'll also need the ScriptExtenderSettings.json file)
Now you should have a working BG3SE setup. (But no setup for BG3MM yet)

3. Goto "%AppData%\Local\" Create folder named "BG3ScriptExtender" then in that created folder, create a folder named "ScriptExtender"(any name would work too I guess). Then inside that ScriptExtender folder create another folder with any name, say "Current". In that Current folder extract the "DWrite.dll" file from "ManualInstall.zip" and rename the "DWrite.dll" to "BG3ScriptExtender.dll". So finally it'd look like this "%AppData%\Local\BG3ScriptExtender\ScriptExtender\Current\BG3ScriptExtender.dll".

4. Now BG3MM should recognise the BG3SE version from there.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
