### ISSUE TITLE
Does not enable Achievements

### ISSUE THREAD

**Issue by qawasx** [Norbyte/bg3se#15]
I tested this with the "No Penny Required" and the "Fetch Quest" Achievements.
Both did not pop. I own the game on steam. 
i tried both the version with the console and the one without. both do not activate achievements.

**Comment by SkebbZ** [comment]
<html><body>
<p dir="auto">The following configuration variables can be set in the <code>ScriptExtenderSettings.json</code> file:</p>


Variable | Type | Description
-- | -- | --
CreateConsole | Boolean | Creates a console window that logs extender internals. Mainly useful for debugging.
EnableLogging | Boolean | Enable logging of Osiris activity (rule evaluation, queries, etc.) to a log file.
LogRuntime | Boolean | Log extender console and script output to a log file.
LogCompile | Boolean | Log Osiris story compilation to a log file.
LogFailedCompile | Boolean | Log errors during Osiris story compilation to a log file.
LogDirectory | String | Directory where the generated Osiris logs will be stored. Default is My Documents\OsirisLogs
EnableExtensions | Boolean | Make the Osiris extension functionality available ingame or in the editor.
SendCrashReports | Boolean | Upload minidumps to the crash report collection server after a game crash.
DumpNetworkStrings | Boolean | Dumps the NetworkFixedString table to LogDirectory. Mainly useful for debugging desync issues.
DeveloperMode | Boolean | Enables various debug functionality for development purposes.
DisableModValidation | Boolean | Disable module hashing when loading modules.
**EnableAchievements** | Boolean | Re-enable achievements for modded games.
EnableDebugger | Boolean | Enables the Osiris debugger interface
DebuggerPort | Integer | Port number the Osiris debugger will listen on (default 9999)
EnableLuaDebugger | Boolean | Enables the Lua debugger interface
LuaDebuggerPort | Integer | Port number the Lua debugger will listen on (default 9998)


</body>
</html>

**Comment by Fe-n** [comment]
I am expanding/asking for clarification on this.  I've made sure that `ScriptExtenderSettings.json` correctly has the setting for achievements to be enabled.  I also see in the BG3SE Debug Console that achievements should be working ("Modded achievements enabled.").  However, when I attempt to load a game, I get a pop-up dialogue from the game telling me that achievements will be disabled because I am playing with mods.

I am not in a spot to easily test whether or not the pop-up is accurate (i.e. cannot easily attempt to get an achievement), so I would like clarification on whether or not this pop-up is expected when the SE option is functioning correctly.  If it is not, then there is a bug.  If it is expected, however, then I think it would save a lot of people a lot of headache if there was some sort of notice letting people know that the pop-up is expected and that despite it, achievements will still function.

Anyone who knows, please clarify which is the case:  (A) a bug in SE exists preventing achievements from being enabled or (B) the pop-up is expected behavior and does not accurately reflect whether or not achievements will function.

**Comment by SkebbZ** [comment]
The popuo is always there with mods. If you install ImprovedUI, it will suppress the message.

**Comment by SkebbZ** [comment]
If you for some reason still can't get achievements, just get the achievement enabler from nexus to be sure.

**Comment by Fe-n** [comment]
> The popup is always there with mods. If you install ImprovedUI, it will suppress the message.
> 
> https://www.nexusmods.com/baldursgate3/mods/366?tab=description

Thank you for the clarification!  I feel this should probably be mentioned in the repo's README, since it seems like a common point of confusion.  Even just today someone opened a new issue about it.  I've also seen questions about it on the repo for the mod loader (which relies on BG3SE and allows management of it from within the mod loader).

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
