### ISSUE TITLE
Game cannot launch after the hotfix 12

### ISSUE THREAD

**Issue by ssk1997** [Norbyte/bg3se#195]
After the hotfix 12, the game failed to launch, it seems to conflict with the native mod loader, only by deleting the script extender or the native mod loader can the game start normally.

**Comment by Galthariel** [comment]
This conclusion came after several tests and troubleshooting. While it is true that deleting BG3SE or NML makes the game launch it seems that what is causing the issue is another mod that uses NML which in my case was Achievement Enabler (BG3AchievementEnabler.dll). Deleting that dll from the Native Mods folder fixed the issue. As I said, In my case, it was Achievement Enabler but it could be any other mod that requires NML.

I hope that helps.

**UPDATE:** Using the Test version of Achievement Enabler works but I haven't played much to fully test. If you read the posts in the Achievement Enabler Mod there is a link there to download the Test version.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
