### ISSUE TITLE
BG3 script extender wont' initialize?

### ISSUE THREAD

**Issue by tuf80631** [Norbyte/bg3se#244]
BG3Ext v9 built on Nov  5 2023 00:50:24
Game version v4.44.94.476 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'EoCServer2/EoCClient2' [CRITICAL]
No match found for mapping 'ecl::GameStateMachine::Update' [CRITICAL]
No match found for mapping 'esv::GameStateThreaded::GameStateWorker::DoWork' [CRITICAL]
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'RPGStats::Load'
No match found for mapping 'KillLauncher'
ScriptExtender::Initialize: Could not load libraries; skipping scripting extension initialization.
Library startup took 749 ms
ecl::ScriptExtender::OnGameStateChanged(): Loaded module
bg3se::ExtensionStateBase::LoadConfigs(): Mod manager not available
bg3se::ExtensionStateBase::LoadConfigs(): Mod manager not available
No match found for mapping 'ls::ModuleSettings::IsModded'
LibraryManager::PostStartupFindLibraries() took 101 ms
STARTUP ERROR: A severe error has occurred during Script Extender initialization. Extension features will be unavailable.

**Comment by Varriount** [comment]
Could you please run the attached batch file, to generate a hash list of all your game files? (you'll need to rename it to give it a ".bat" extension, as GitHub won't allow uploading batch files)

**Comment by tuf80631** [comment]
[Uploading BG3 File Hashes.txt…]()

**Comment by tuf80631** [comment]
[BG3 File Hashes.txt](https://github.com/Norbyte/bg3se/files/14078512/BG3.File.Hashes.txt)

**Comment by Varriount** [comment]
Some notes:
- Your script extender version is quite outdated:
  ```
  BG3Ext v9 built on Nov 5 2023 00:50:24
  ```
- You have a both a `ScriptExtenderSettings.json` and a `ScriptExtenderUpdaterConfig.json` in your BG3 installation's `bin` folder.

Could you upload those two files here, and also try temporarily deleting/renaming them? There's a good chance that the error you are seeing is because those files are preventing your version of Script Extender from updating, leading to an incompatibility with your game installation.

**Comment by tuf80631** [comment]
looks like it worked. thanks!
