### ISSUE TITLE
 Missing inventory

### ISSUE THREAD

**Issue by DexManzana** [Norbyte/bg3se#270]
Hello, after installing I think the updated SE is correct, I have seen that my inventory does not appear on the tab or on the i key, is there a way to solve this?

**Comment by axel-de-block** [comment]
I had this issue with BCPP and Better Containers from Pavelk installed. Removing those fixed it, so it does not appear to be a SE issue at the moment.

**Comment by Pyr0blad3** [comment]
just wait till UI mods get updated.

**Comment by fantista** [comment]
I am also having the same issue and have all of the updated UI mods reinstalled

**Comment by Jack7on7** [comment]
I fixed that) 
I'm used this two mods:
[Better Containers](https://www.nexusmods.com/baldursgate3/mods/1416)
[Easier Text](https://www.nexusmods.com/baldursgate3/mods/1037)
and they were updated today, the problem is that for some reason the Better containers are not displayed in the BG3 Mod Manager, and Easier Text one must be dropped into the folder, so they had to be updated manually, as soon as I updated them, everything worked)

**Comment by fantista** [comment]
Unfortunately I did not have either of those installed. But I will keep looking for the issue

**Comment by fantista** [comment]
I found it yesterday after going through each mod. I forgot I had the plusUI.pak file in the game directory and i never put it in mod manager. After the testing, that mod is still outdated and have Uninstalled it and it works fine now!

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
