### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Amaund** [Norbyte/bg3se#281]
With just the SE installed, the game crashes at 50% load past the MM, and I keep getting a pop up saying the SE has crashed.

**Comment by waterscaped** [comment]
Same here

**Comment by Varriount** [comment]
Alas, we can't read minds, nor magically see the state of your games. Could you list which mods you are running?

**Comment by Amaund** [comment]
JUST the SE

**Comment by Varriount** [comment]
Could you please run [this](https://gist.githubusercontent.com/Varriount/8a29c2f4d5fcbb5e7903bb24f6287b0a/raw/0fddf594089475391f1ebece4a3b9ef6bc3bac82/Generate%2520BG3SE%2520Diagnostics.bat) batch script, and attach the results? (Download the file, or copy the contents into a new file, and rename the new file so that it has a `.bat` extension).

**Comment by Amaund** [comment]
Nothing happened

**Comment by Varriount** [comment]
No console window appeared, and no file was generated in your TEMP folder?

**Comment by Amaund** [comment]
TEMP folder?

**Comment by Amaund** [comment]
A console window opened for about 2 seconds, the closed, and that is all. I have no TEMP folder for bg3, and idk how they generate.

**Comment by Norbyte** [comment]
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.
