### ISSUE TITLE
Script Extender Error Code

### ISSUE THREAD

**Issue by Bashworth99** [Norbyte/bg3se#29]
Once I download the Script Extender, I get a message saying "Script Extender update failure; make sure your connected to the internet and try again. Unable to download manifest (35) SSL connect error." Please help.

**Comment by antarek** [comment]
Exact same error here.

**Comment by AliiGee** [comment]
Same problem here, when I search the error message this is the only thread that comes up, can't find any other mention of this error message in regards to BG3.

Adding some context in hopes that it gives someone down the road an idea of how to help. I've tried using the version and instructions found here, (https://github.com/Norbyte/bg3se/releases) specifically downloading the "BG3SE-Updater-with-Console-v3.zip " version.

I've also tried using the download and both sets of instructions found here (https://www.nexusmods.com/baldursgate3/articles/169). The instructions in that post say to use the BG3 Mod Manager, other instructions in the comments are for manual extraction. I've tried both with and without a comma after the word "true" in the following line because I saw both on that page and figured it was worth a shot.

"{
  "CreateConsole": true
}"

Both result in the same error message. 

"Script extender update failed; make sure you're connected to the internet and try again. Unable to download manifest: (35) SSL connect error"

I have uninstalled all mods from the mod manager and I cleared any script extender files from my .bin folder between each attempt.

Thanks for taking the time to read, and thanks to anyone who is willing to help out.

**Comment by AliiGee** [comment]
Of course this happens right after I post the last comment but I think I found a fix in a thread about a different issue.

I disconnected from my usual wifi network and instead used a mobile hotspot on my phone and after the Larian splash screen stuttered for a bit the script extender console opened alongside the game. When I disconnect from the hotspot and use my usual network the error message is back after the splash screen but the console still opens with the game.

I'm not very technically skilled so I'm not sure what's going on, and I'm sorry that I can't give any helpful details about what's going on under the hood, but I hope this helps anyone else out there having the same issue.

**Comment by Norbyte** [comment]
The CDN behind the update server was changed, and this seems to no longer be an issue, closing.

**Comment by GiMark00** [comment]
@Norbyte This is the only place where I found posts about this problem, hope you don't mind if I text here. Now I'm facing the same problem and I don't understand what's wrong. It doesn't matter if I run the game with mods or without, SE just doesn't want to update and gives this error. I've updated git, disabled antivirus and any vpn but nothing helps. Could you please help with this or maybe tell me what exactly is wrong? 

![Image](https://github.com/user-attachments/assets/a2768427-2f07-414d-9a01-f64f48fd9477)
