### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by Liareth** [Norbyte/bg3se#6]
Hiya!

Thanks for the cool project.

I've spent the last couple hours dealing with dependencies etc to make it build. Alas, trying to run the thing after I got it to build gave me a bunch of memory corruption errors, and I figured I was wasting my time going any further without dropping a message here. Based on what I've seen while trying to make it build, I get the feeling it depends on symbols provided by Larian, so I'm not sure how much I can help, but I would like to get involved if I can.

If you're curious what terrible sins I had to commit to make the thing build, you can check here: https://github.com/Liareth/bg3se/commit/55d905202cbcca9414de603919a0492ddba6f0bb

Please let me know if you're looking for help, and if you are, how I can get involved! Thank you.

**Comment by Norbyte** [comment]
Hi,

I'm not sure what could cause the memory corruption errors, it might be because of dependencies being linked with different VS versions. 
Sadly we don't have any symbol tables from Larian, everything has to be mapped manually by decompiling bg3.exe.

> If you're curious what terrible sins I had to commit to make the thing build, you can check here:
The terrible sins don't look so terrible by the way :)

> Please let me know if you're looking for help, and if you are, how I can get involved! Thank you.
The biggest challenge right now is mapping the .exe and finding the structures/functions needed for supporting further work; this currently includes the stats system, entity system, resource manager and major entity components.
It is quite time-consuming work and requires familiarity with IDA or reversing in general.
